<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="IMS_Customer.aspx.cs" Inherits="InvantoryManagementSystem.UI.IMS_Customer" %>

<%@ Register Assembly="CrystalDecisions.Web, Version=13.0.3500.0, Culture=neutral, PublicKeyToken=692fbea5521e1304" Namespace="CrystalDecisions.Web" TagPrefix="CR" %>


<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">


    <fieldset>
        <legend>Order Form</legend>
        <table class="table table-border">
            <tr>
                <td style="width: 127px">
                    <asp:DropDownList ID="dropdown_customerid" runat="server" Height="35px" Width="170px" BackColor="WhiteSmoke" AutoPostBack="true" ></asp:DropDownList>
                </td>

                <td style="width: 127px">
                    <asp:DropDownList ID="dropdown_productname" runat="server" Height="35px" Width="170px" BackColor="WhiteSmoke" AutoPostBack="true" OnSelectedIndexChanged="dropdown_productname_SelectedIndexChanged"></asp:DropDownList>
                </td>

                <td style="width: 127px">
                    <asp:Label ID="lblproduct_quantity" runat="server" Text="Product Quantity"></asp:Label>

                </td>

                <td>
                    <asp:TextBox ID="txtproduct_quantity" runat="server" CssClass="form-control" Height="35px" Width="80px"></asp:TextBox>
                </td>
                <td>
                    <asp:RegularExpressionValidator runat="server" ID="regQuantity" ForeColor="Red" ControlToValidate="txtproduct_quantity" ErrorMessage="Insert In Correct Format" ValidationExpression="^[0-9]+(\.[0-9][0-9]?)?"></asp:RegularExpressionValidator>
                </td>

                <td style="width: 127px">
                    <asp:Label ID="lblproduct_unitprice" runat="server" Text="Product Unit Price"></asp:Label>

                </td>
                <td>
                    <asp:TextBox ID="txtproduct_unitprice" runat="server" CssClass="form-control" Height="35px" Width="80px"></asp:TextBox>
                </td>
                <td>
                    <asp:RegularExpressionValidator runat="server" ID="regPrice" ForeColor="Red" ControlToValidate="txtproduct_unitprice" ErrorMessage="Insert In Correct Format" ValidationExpression="^[0-9]+(\.[0-9][0-9]?)?"></asp:RegularExpressionValidator>
                </td>

                <td style="width: 127px">
                    <asp:Label ID="lblbuydate" runat="server" Text="Buy Date"></asp:Label>

                </td>
                <td>
                    <asp:TextBox ID="txtbuydate" runat="server" CssClass="form-control" Height="35px" Width="170px"></asp:TextBox>
                    <asp:ImageButton ID="imgbtn_buydate" runat="server" ImageUrl="~/Photos/clndr.png" Height="50px" Width="50px" OnClick="imgbtn_buydate_Click" />
                    <asp:Calendar ID="Calendar_buydate" runat="server" BackColor="White" BorderColor="Black" DayNameFormat="Shortest" Font-Names="Times New Roman" Font-Size="10pt" ForeColor="Black" Height="200px" NextPrevFormat="FullMonth" TitleFormat="Month" Width="200px" OnSelectionChanged="Calendar_buydate_SelectionChanged">
                        <DayHeaderStyle BackColor="#CCCCCC" Font-Bold="True" Font-Size="7pt" ForeColor="#333333" Height="10pt" />
                        <DayStyle Width="14%" />
                        <NextPrevStyle Font-Size="8pt" ForeColor="White" />
                        <OtherMonthDayStyle ForeColor="#999999" />
                        <SelectedDayStyle BackColor="#CC3333" ForeColor="White" />
                        <SelectorStyle BackColor="#CCCCCC" Font-Bold="True" Font-Names="Verdana" Font-Size="8pt" ForeColor="#333333" Width="1%" />
                        <TitleStyle BackColor="Black" Font-Bold="True" Font-Size="13pt" ForeColor="White" Height="14pt" />
                        <TodayDayStyle BackColor="#CCCC99" />
                    </asp:Calendar>
                </td>
            </tr>

        </table>

        <asp:Button ID="Add" runat="server" CssClass="btn btn-primary" Text="Add Product" OnClick="Add_Click" UseSubmitBehavior="false" />

    </fieldset>

    <input type="button" id="btnAddUser" class="btn btn-primary" value="Add New Customer" style="float: right;" />

    <br />
    <br />
    <br />

    <fieldset>
        <legend>Order Details</legend>
        <asp:GridView ID="gv_orderdetails" runat="server" AutoGenerateColumns="false" CssClass="table table-hover table-bordered" ShowFooter="true" AutoGenerateSelectButton="true" OnSelectedIndexChanged="gv_orderdetails_SelectedIndexChanged" AutoGenerateDeleteButton="true" OnRowDeleting="gv_orderdetails_RowDeleting">

            <Columns>

                <asp:TemplateField HeaderText="">
                    <ItemTemplate>
                        <asp:Label ID="lblid" Text='<%# Eval("id") %>' runat="server" />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Customer ID">
                    <ItemTemplate>
                        <asp:Label ID="lbl_customerid" Text='<%# Eval("customerid") %>' runat="server"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Name">
                    <ItemTemplate>
                        <asp:Label ID="lbl_Name" Text='<%# Eval("Name") %>' runat="server"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Mail">
                    <ItemTemplate>
                        <asp:Label ID="lbl_Mail" Text='<%# Eval("Mail") %>' runat="server"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Phone">
                    <ItemTemplate>
                        <asp:Label ID="lbl_Phone" Text='<%# Eval("Phone") %>' runat="server"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Address">
                    <ItemTemplate>
                        <asp:Label ID="lbl_Address" Text='<%# Eval("Address") %>' runat="server"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Product Name">
                    <ItemTemplate>
                        <asp:Label ID="lbl_product_name" Text='<%# Eval("product_name") %>' runat="server"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Date">
                    <ItemTemplate>
                        <asp:Label ID="lbl_buydate" Text='<%# Eval("buy_date") %>' runat="server"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Product Quantity">
                    <ItemTemplate>
                        <asp:Label ID="lbl_product_quantity" Text='<%# Eval("product_quantity") %>' runat="server"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Product Unit Price">
                    <ItemTemplate>
                        <asp:Label ID="lbl_product_unitprice" Text='<%# Eval("product_unitprice") %>' runat="server"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Amount">
                    <ItemTemplate>
                        <asp:Label ID="lbl_Amount" Text='<%# Eval("totalamount") %>' runat="server"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>

            </Columns>

        </asp:GridView>

        <asp:Button ID="btnInvoice" runat="server" CssClass="btn btn-default" Text="Invoice" Visible="false" OnClick="btnInvoice_Click" UseSubmitBehavior="false" />

        <asp:Button ID="btnConfirm" runat="server" Text="Confirm" CssClass="btn btn-success" Visible="false" OnClick="btnConfirm_Click" Style="float: right;" UseSubmitBehavior="false" />

    </fieldset>

    <br />
    <br />

    <formview>
        <script type="text/javascript" src='https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.3.min.js'></script>
        <script type="text/javascript" src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/js/bootstrap.min.js'></script>
        <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/css/bootstrap.min.css'
            media="screen" />
        &nbsp;<script type="text/javascript">
                  $(function () {
                      $("#btnAddUser").click(function () {
                          $('#AddUserModal').modal('show');
                      });
                  });
        </script>
        <div class="modal fade" id="AddUserModal" tabindex="-1" role="dialog" aria-labelledby="ModalTitle"
            aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                            &times;</button>
                        <h4 class="modal-title" id="ModalTitle">Customer Information</h4>
                    </div>
                    <div class="modal-body">
                        <table>
                            <tr>
                                <td>
                                    <label for="txtCustomerId">
                                        CustomerId</label>
                                    <asp:TextBox ID="txtCustomerId" runat="server" CssClass="form-control" placeholder="Enter CustomerID"
                                        required />
                                    <br />
                                </td>
                                <td>
                                    <label for="txtName">
                                        User Name</label>
                                    <asp:TextBox ID="txtName" runat="server" CssClass="form-control" placeholder="Enter Name"
                                        required />
                                    <br />
                                </td>
                                <td>
                                    <label for="txtPhone">
                                        Phone</label>
                                    <asp:TextBox ID="txtPhone" runat="server" CssClass="form-control" placeholder="Enter Phone Number"
                                        required />
                                    <br />
                                </td>
                            </tr>

                            <tr>
                                <td>
                                    <label for="txtMail">
                                        Email</label>
                                    <asp:TextBox ID="txtMail" runat="server" CssClass="form-control" TextMode="Email" placeholder="Enter Email"
                                        required />
                                    <br />
                                </td>
                                <td>
                                    <label for="txtAddress">
                                        Address</label>
                                    <asp:TextBox ID="txtAddress" runat="server" CssClass="form-control" placeholder="Enter Address"
                                        required />
                                    <br />
                                </td>
                            </tr>
                        </table>

                        <div id="dvMessage" runat="server" visible="false" class="alert alert-danger">
                            <strong>Error!</strong>
                            <asp:Label ID="lblMessage" runat="server" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <asp:Button ID="btnAdd" Text="Add" runat="server" OnClick="btnAdd_Click" Class="btn btn-primary" />
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            Close</button>
                    </div>
                </div>
            </div>
        </div>
    </formview>

</asp:Content>
