<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="IMS_Supplier.aspx.cs" Inherits="InvantoryManagementSystem.UI.IMS_Supplier" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <fieldset>
        <legend>Product Supply details
        </legend>


        <table class="table table-border">
            <tr>
                <td style="width: 127px">
                    <asp:Label ID="lblsupply_id" runat="server" Text="Supply ID"></asp:Label>

                </td>
                <td>
                    <asp:TextBox ID="txtsupply_id" runat="server" CssClass="form-control" Height="35px" Width="80px"></asp:TextBox>
                </td>

                <td style="width: 127px">
                    <asp:Label ID="lblname" runat="server" Text="Supplier Name"></asp:Label>

                </td>
                <td>
                    <asp:TextBox ID="txtname" runat="server" CssClass="form-control" Height="35px" Width="170px"></asp:TextBox>
                </td>

                <td style="width: 127px">
                    <asp:Label ID="lblphn" runat="server" Text="Phone Number"></asp:Label>

                </td>
                <td>
                    <asp:TextBox ID="txtphone" runat="server" CssClass="form-control" Height="35px" Width="150px"></asp:TextBox>
                </td>
            </tr>

        </table>
    </fieldset>
    <fieldset>
        <table class="table">
            <tr>
                <td>
                    <asp:Button ID="btnAdd" runat="server" Text="Add" CssClass="btn btn-success" OnClick="btnAdd_Click" Width="90px" />
                </td>
                <td>
                    <asp:Button ID="btnUpdate" runat="server" Text="Update" CssClass="btn btn-primary" OnClick="btnUpdate_Click" Width="90px" />
                </td>
            </tr>
        </table>
    </fieldset>

    <br />
    <br />

    <fieldset>
        <div style="height: 500px; width: 1200px; overflow: auto;">
            <asp:GridView ID="gv_supplydetails" runat="server" AutoGenerateColumns="false" CssClass="table table-hover table-bordered" AutoGenerateSelectButton="true" AutoGenerateDeleteButton="true" OnRowEditing="gv_supplydetails_RowEditing" OnRowCancelingEdit="gv_supplydetails_RowCancelingEdit" OnRowDeleting="gv_supplydetails_RowDeleting" OnSelectedIndexChanged="gv_supplydetails_SelectedIndexChanged">
                <Columns>
                    <asp:TemplateField HeaderText="Supplier ID">
                        <ItemTemplate>
                            <asp:Label ID="lblsupply_id" Text='<%# Eval("supplier_id") %>' runat="server">
                            </asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Supplier Name">
                        <ItemTemplate>
                            <asp:Label ID="lblsupply_name" Text='<%# Eval("name") %>' runat="server">
                            </asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Phone">
                        <ItemTemplate>
                            <asp:Label ID="lblphone" Text='<%# Eval("phone") %>' runat="server">
                            </asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
        </div>
    </fieldset>
</asp:Content>
